openapi: 3.1.0
info:
  title: Mario Personal MCP API
  version: 1.0.0
servers:
  - url: https://mcp.mariomayerle.com
paths:
  /resources:
    get:
      summary: Retrieve all public data
      operationId: getAllResources
      responses:
        '200':
          description: Public data retrieved
  /resources/linkedin:
    get:
      summary: Retrieve LinkedIn profile data
      operationId: getLinkedInData
      responses:
        '200':
          description: LinkedIn data retrieved
  /resources/github:
    get:
      summary: Retrieve GitHub repositories
      operationId: getGitHubRepos
      responses:
        '200':
          description: GitHub repositories retrieved
  /resources/blogposts:
    get:
      summary: Retrieve blog posts
      operationId: getBlogPosts
      responses:
        '200':
          description: Blog posts retrieved
  /tools/get_project_details:
    get:
      summary: Retrieve details of specific repo
      operationId: getProjectDetails
      parameters:
        - in: query
          name: repo_name
          required: true
          schema:
            type: string
          description: Name of the repository
      responses:
        '200':
          description: Project details retrieved
        '404':
          description: Project not found
